INSERT INTO lti_permissions_ltipermission (permission, school_id, canvas_role, allow) VALUES
('lti_emailer_view', '*', 'Account Observer', TRUE),
('lti_emailer_view', '*', 'AccountAdmin', TRUE),
('lti_emailer_view', '*', 'Account Admin', TRUE),
('lti_emailer_view', '*', 'Course Head', TRUE),
('lti_emailer_view', '*', 'Course Support Staff', TRUE),
('lti_emailer_view', '*', 'Department Admin', TRUE),
('lti_emailer_view', '*', 'DesignerEnrollment', TRUE),
('lti_emailer_view', '*', 'Faculty', TRUE),
('lti_emailer_view', '*', 'Guest', FALSE),
('lti_emailer_view', '*', 'Harvard-Viewer', FALSE),
('lti_emailer_view', '*', 'Help Desk', TRUE),
('lti_emailer_view', '*', 'Librarian', TRUE),
('lti_emailer_view', '*', 'ObserverEnrollment', FALSE),
('lti_emailer_view', '*', 'SchoolLiaison', TRUE),
('lti_emailer_view', '*', 'Prospective Enrollee', FALSE),
('lti_emailer_view', '*', 'StudentEnrollment', FALSE),
('lti_emailer_view', '*', 'TaEnrollment', TRUE),
('lti_emailer_view', '*', 'TeacherEnrollment', TRUE),
('lti_emailer_view', '*', 'Teaching Staff', TRUE),
('lti_emailer_send_all', '*', 'Account Observer', FALSE),
('lti_emailer_send_all', '*', 'AccountAdmin', FALSE),
('lti_emailer_send_all', '*', 'Account Admin', FALSE),
('lti_emailer_send_all', '*', 'Course Head', TRUE),
('lti_emailer_send_all', '*', 'Course Support Staff', TRUE),
('lti_emailer_send_all', '*', 'Department Admin', FALSE),
('lti_emailer_send_all', '*', 'DesignerEnrollment', TRUE),
('lti_emailer_send_all', '*', 'Faculty', TRUE),
('lti_emailer_send_all', '*', 'Guest', FALSE),
('lti_emailer_send_all', '*', 'Harvard-Viewer', FALSE),
('lti_emailer_send_all', '*', 'Help Desk', FALSE),
('lti_emailer_send_all', '*', 'Librarian', FALSE),
('lti_emailer_send_all', '*', 'ObserverEnrollment', FALSE),
('lti_emailer_send_all', '*', 'SchoolLiaison', FALSE),
('lti_emailer_send_all', '*', 'Prospective Enrollee', FALSE),
('lti_emailer_send_all', '*', 'StudentEnrollment', FALSE),
('lti_emailer_send_all', '*', 'TaEnrollment', TRUE),
('lti_emailer_send_all', '*', 'TeacherEnrollment', TRUE),
('lti_emailer_send_all', '*', 'Teaching Staff', TRUE);
